<header>
        <nav>
            <div class="dropdown">
                <button class="drop"> <img src="./images/logo.png" alt="menu"></button>
                <div class="dropdown-content">
                    <a href="index.php">Home</a>
                    <a href="jobs.php">Jobs Descriptions</a>
                    <a href="apply.php">Applications</a>
                    <a href="enhancements.php">Enhancements</a>
                    <a href="about.php">About Us</a>
                </div>
        </nav>
</header>
<?php
require_once("./settings.php");
